[package]
name = "valence_protocol"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"

[dependencies]
aes = { version = "0.7.5", optional = true }
anyhow = "1.0.66"
bitfield-struct = "0.3.1"
byteorder = "1.4.3"
bytes = "1.2.1"
cfb8 = { version = "0.7.1", optional = true }
flate2 = { version = "1.0.24", optional = true }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
tracing = "0.1.37"
uuid = "1.2.1"
valence_derive = { version = "0.1.0", path = "../valence_derive" }
valence_nbt = { version = "0.5.0", path = "../valence_nbt" }

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
rand = "0.8.5"
criterion = "0.4.0"
valence_protocol = { version = "0.1.0", path = ".", features = ["compression"] }

[build-dependencies]
anyhow = "1.0.65"
heck = "0.4.0"
proc-macro2 = "1.0.43"
quote = "1.0.21"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

[features]
encryption = ["dep:aes", "dep:cfb8"]
compression =  ["dep:flate2"]
