[package]
name = "valence_scoreboard"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
valence_core.workspace = true
valence_entity.workspace = true
valence_layer.workspace = true
valence_packet.workspace = true
tracing.workspace = true
