edition = "2021"
unstable_features = true
wrap_comments = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Lower"
format_strings = true
use_field_init_shorthand = true
use_try_shorthand = true
