[package]
name = "valence_anvil"
description = "Anvil world format support for Valence"
documentation.workspace = true
readme = "README.md"
license.workspace = true
keywords = ["anvil", "minecraft", "deserialization"]
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
byteorder.workspace = true
flate2.workspace = true
flume.workspace = true
lru.workspace = true
num-integer.workspace = true
thiserror.workspace = true
tracing.workspace = true
valence_biome.workspace = true
valence_client.workspace = true
valence_core.workspace = true
valence_entity.workspace = true
valence_layer.workspace = true
valence_nbt.workspace = true
