[package]
name = "valence"
version = "0.2.0+mc1.19.3"
edition = "2021"
description = "A framework for building Minecraft servers in Rust."
repository = "https://github.com/rj00a/valence"
readme = "README.md"
license = "MIT"
keywords = ["minecraft", "gamedev", "server", "ecs"]
categories = ["game-engines"]
build = "build/main.rs"
authors = ["Ryan Johnson <ryanj00a@gmail.com>"]

[dependencies]
#bevy_mod_debugdump = "0.7.0"
anyhow = "1.0.65"
arrayvec = "0.7.2"
async-trait = "0.1.60"
base64 = "0.21.0"
bevy_app = "0.10"
bevy_ecs = "0.10"
bitfield-struct = "0.3.1"
bytes = "1.2.1"
flume = "0.10.14"
glam = "0.22.0"
hmac = "0.12.1"
num = "0.4.0"
parking_lot = "0.12.1"
paste = "1.0.11"
rand = "0.8.5"
rsa = "0.7.2"
rsa-der = "0.3.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
sha1 = { version = "0.10.5", features = ["oid"] }
sha2 = { version = "0.10.6", features = ["oid"] }
thiserror = "1.0.35"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "1.1.2", features = ["serde"] }
valence_nbt = { version = "0.5.0", path = "../valence_nbt", features = [
    "uuid",
] }
valence_protocol = { version = "0.1.0", path = "../valence_protocol", features = [
    "encryption",
    "compression",
] }

[dependencies.reqwest]
version = "0.11.12"
default-features = false
# Avoid OpenSSL dependency on Linux.
features = ["rustls-tls", "json"]

[dev-dependencies]
approx = "0.5.1"
glam = { version = "0.22.0", features = ["approx"] }
noise = "0.8.2"
tracing-subscriber = "0.3.16"

[build-dependencies]
anyhow = "1.0.65"
heck = "0.4.0"
proc-macro2 = "1.0.43"
quote = "1.0.21"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
rayon = "1.5.3"
num = "0.4.0"
