[package]
name = "playground"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.65"
glam = "0.23.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
valence_protocol.workspace = true
valence.workspace = true
