[package]
name = "playground"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
valence_math.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
valence_core.workspace = true
valence.workspace = true